# Generated by Django 5.1.4 on 2024-12-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_chamados_status_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
