# Generated by Django 5.1.4 on 2024-12-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='tipo_equipamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
