# Generated by Django 5.1.4 on 2025-03-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='quantidade_resma',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
