# Generated by Django 5.1.4 on 2026-03-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_chamados_quantidade_resma'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
